# MIT License
# Copyright (C) 2022 Artem Kuznetsov <ArKuznetsov@gmail.com> and contributors
# All rights reserved.

name: Подготовка релиза и публикация в хабе
# Только события создания и изменения релиза
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PACKAGE_MASK: ClientSSH-*.ospx
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [clientSSH]
        oscript_version: ['1.8.4']
        
    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v2.3.4

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          cd build
          opm install opm
          opm install
          cd ..

      # Сборка проекта
      - name: Сборка проекта
        run: ./build/build.bat

      # Заливка артефактов
      - name: Заливка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: package.zip
          path: ./build/${{ env.PACKAGE_MASK }}

      # Заливка в релиз
      - name: Заливка в релиз
        uses: AButler/upload-release-assets@v1.0
        with:
          files: ./build/${{ env.PACKAGE_MASK }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Публикация в hub.oscript.io
      - name: Публикация в hub.oscript.io
        run: opm push -f ./build/${{ env.PACKAGE_MASK }} --token ${{ env.TOKEN }} -c stable
        env:
          TOKEN: ${{ secrets.OSHUB_TOKEN }}
